const router = require('express').Router()
const authorizer = require('../service/AutorizerService')
const controller = require('../controller/GatewayController')
const startTest = require('../controller/TestController')
const zipCodeController = require('../controller/ZipCodeSearchController')

router.use(authorizer)
router.delete('/:uri/:id/:param?', controller.deleteParser)
router.get('/me', controller.getMe)
router.get('/start-auction-test', startTest)
router.get('/zip-codes', zipCodeController.search)
router.get('/:uri', controller.getParser)
router.get('/:uri/:id', controller.getParser)
router.patch('/:uri/:id/:param?', controller.patchParser)
router.patch('/:uri', controller.patchParser)
router.post('/:uri', controller.postParser)
router.post('/:uri/:id', controller.postParser)
router.put('/:uri/:id/:param?', controller.putParser)

module.exports = router
